
""" MODULLAR"""



# print(range(1, 10))


# kvdrt_tmni = 300
# kvdrt_yuzi = kvdrt_tmni**56
# print(kvdrt_yuzi)



# ism = 'Jobir'
# print(type(ism))
# yosh = 36
# print(type(yosh))


# ism = input('ismingizni kiriting:>>>').title()
# t_yil = int(input("Tug'ilgan yilingizni kiriting: "))
# t_yil = t_yil
# yosh = 2024 - t_yil #
# int("Assalomu alaykum" + "Sizning " + str(ism) + "va" + str(yosh) + " yoshda ekansiz")
# print(f"Assalomu alaykum  {ism} siz {yosh} yoshda ekansiz")



#     meva = "    olma   "
#     print("Men " + meva.lstrip() + " yaxshi ko'raman")
#     print("Men " + meva.rstrip() + " yaxshi ko'raman")
#     print("Men " + meva.strip() + " yaxshi ko'raman")
#     print("Men " + meva +" yaxshi ko'raman")


# son1 = int(input("birinchi sonni kiriting:>>>>"))
# son2 = int(input("Endi ikkinchi sonni kiriting:>>>"))
# kvadrat = son1 **2
# kubi =  son2 **3
# print(f"Assalomu alaykum {son1} {kvadrat}  {son2} {kubi}  :")



# """1-mashq"""
# ism = input("ismingizni kiritin  :")
# familiya = input("familiyangizni kiriting :")
# otam = input("otangizning isnmini kiriting :")
# yosh = int(input("yoshingizni kiriting :"))
# sinf = int(input("sinfingizni kiriting :"))
# print(f"assalomu alaykum {ism} {familiya} otangizning ismi {otam} sining yoshingiz {yosh}da sizning sinfingiz {sinf} malumot uchun raxmat")


"""2-mashq
 Son va matn deb nomlangan
 o’zgaruvchilar yarating va ularni kommenga oling."""

# son = 555
# matn = 'malaka'
# print(f"{son} {matn}")



"""3-mashq"""
# print(2*(265/5)+(751/6))


"""4-mashq"""

# print((8934*34)/(62*42))

"""5-mashq"""


# otam = 'bobur'
# onam = 'guli'
# ukam = 'bilol'
# dostim = 'akbar'
# print(f"otamning ismi {otam}, onaqmning ismi {onam}, ukamning ismi {ukam}, va dostimning ismi {dostim} ")




"""1-mashq"""
# print("Ahmadning ""yuvosh"" mushugi meni korsa, yugurib keladi.")


"""2-mashq"""

# print((93434+94903)-22344+7363)


"""3-mashq"""

# mashina =  "     BMW    "
# print(" Men " + mashina.lstrip() + " yaxshi koraman ")
# print(" Men " + mashina.strip() + " yaxshi koraman ")
# print(" Men " + mashina.title() + " yaxshi koraman ")
# print(" Men " + mashina.upper() + " yaxshi koraman ")
# print(" Men " + mashina.lower() + " yaxshi koraman ")


# """4-mashq"""







# ism = input("ismingizni kiriting :")
# t_yil = int(input("tugulgan yilingizni kireiting :"))
# yosh = 2025 - t_yil
# print(f"mening ismim{ism}.{t_yil}-yilda tugulganman va hozir {yosh} yoshdaman :")

# import  math
# number = 20202
# print(math.sqrt(number))


# mevalar = ['olma', 'anjir', 'shaftoli', "o'rik"] # mevalar ro'yxati (matnlar)
# narhlar = [12000, 18000, 10900, 22000] # narhlar ro'yxati (sonlar)
# sonlar = ['bir', 'ikki', 3, 4, 5] # sonlar va matnlar aralash ro'yxat
#ismlar = [0,-1] # bo'sh ro'yxat










# mevalar = ['olma', 'anjir', 'shaftoli', "o'rik"] # mevalar ro'yxati (matnlar)
# print("Birinchi meva: ", mevalar[0])
# print("Ikkinchi meva: ", mevalar[1])








# mevalar = ['olma', 'anjir', 'shaftoli', "o'rik"] # mevalar ro'yxati (matnlar)
# print("Birinchi meva: ", mevalar[0].title())
# print("Ikkinchi meva: ", mevalar[1].upper())





# narhlar = [12000, 18000, 10900, 22000]
# print(narhlar[2] + narhlar[3])








# narhlar = [12000, 18000, 10900, 22000]
# narhlar[0] = 13000 # 1-qiymatni 13000 ga o'zgartiramiz
# narhlar[2] = 11000 # 3-qiymatni 11000 ga o'zgartiramiz
# narhlar[3] = narhlar[3]+2000 # 4-qiymatga 2000 qo'shamiz
# print(narhlar)








# mevalar = ['olma', 'anjir', 'shaftoli', "o'rik"]
# mevalar.append("tarvuz") # mevalar ga tarvuz qo'shamiz
# print(mevalar)







# cars = [] # bo'sh ro'yxat yaratamiz
# cars.append('Lacetti') # ro'yxatga Lacetti mashinasini qo'shamiz
# cars.append('Nexia 3') # ro'yxatga Nexia 3 mashinasini qo'shamiz
# cars.append('Cobalt')  # ro'yxatga Cobalt  mashinasini qo'shamiz
# print(cars)




# cars = ['Lacetti', 'Nexia 3', 'Cobalt']
# cars.insert(0, 'Malibu') # 1-o'ringa yangi qiymat qo'shamiz
# print(cars)




# cars.insert(2, 'Damas') # 3-o'ringa yangi qiymat qo'shamiz
# print(cars)




# mevalar = ['olma', 'anjir', 'shaftoli', "o'rik", 'anor']
# del mevalar[1] # 2-element (anjir) ni o'chirib tashlaymiz
# print(mevalar)






# mevalar = ['olma', 'anjir', 'shaftoli', "o'rik", 'anor']
# mevalar.remove('shaftoli') # Ro'yxatdan shaftolini o'chirdik
# print(mevalar)







# hayvonlar = ['it', 'mushuk', 'sigir', 'qo\'y', 'quyon', 'mushuk']
# hayvonlar.remove("mushuk") # Ro'yxatda 2 ta mushuk bor, ulardan birinchisi o'chadi
# print(hayvonlar)








# bozorlik = ["yog'", 'un', 'piyoz', 'banan', "go'sht"]
# mahsulot = bozorlik.pop(3) # Ro'yxatdan banan ni sug'urib olamiz
# print("Men " + mahsulot + " sotib oldim")
# print("Olinmagan mahsulotlar: ", bozorlik)








# git config --global user.name "Your Name"
# git config --global user.email "youremail@domain.com"














